const studentsData = [
  {
    rollno: "A001",
    name: "John Doe",
    standard: "10",
    teacher: "Mr. Smith",
    subject: "Mathematics",
    marks: "85",
    dob: new Date("2005-03-15"),
    parentage: "Jane Doe",
    contact: 1234567890,
    address: "123 Main Street, City, Country",
  },
  {
    rollno: "A002",
    name: "Alice Johnson",
    standard: "8",
    teacher: "Ms. Williams",
    subject: "Science",
    marks: "78",
    dob: new Date("2007-09-20"),
    parentage: "Bob Johnson",
    contact: 9876543210,
    address: "456 Oak Avenue, Town, Country",
  },
  {
    rollno: "A003",
    name: "Emily Smith",
    standard: "12",
    teacher: "Dr. Brown",
    subject: "History",
    marks: "92",
    dob: new Date("2003-11-10"),
    parentage: "Sarah Smith",
    contact: 5556667777,
    address: "789 Elm Street, Village, Country",
  },
  {
    rollno: "A004",
    name: "Michael Davis",
    standard: "9",
    teacher: "Mrs. Johnson",
    subject: "English",
    marks: "80",
    dob: new Date("2006-05-25"),
    parentage: "David Davis",
    contact: 4443332222,
    address: "321 Cedar Road, County, Country",
  },
  {
    rollno: "A005",
    name: "Sophia Wilson",
    standard: "11",
    teacher: "Mr. Anderson",
    subject: "Physics",
    marks: "88",
    dob: new Date("2004-08-12"),
    parentage: "Olivia Wilson",
    contact: 9990001111,
    address: "567 Pine Lane, City, Country",
  },
  {
    rollno: "A006",
    name: "John Doe",
    standard: "7",
    teacher: "Mr. Smith",
    subject: "Mathematics",
    marks: "97",
    dob: new Date("2004-08-12"),
    parentage: "Jane Doe",
    contact: 6283910181,
    address: "123 Main Street, City, Country",
  },
  {
    rollno: "A007",
    name: "Alice Johnson",
    standard: "1",
    teacher: "Ms. Williams",
    subject: "Science",
    marks: "64",
    dob: new Date("2004-08-12"),
    parentage: "Bob Johnson",
    contact: 4514815033,
    address: "456 Oak Avenue, Town, Country",
  },
  {
    rollno: "A008",
    name: "Emily Smith",
    standard: "6",
    teacher: "Dr. Brown",
    subject: "History",
    marks: "76",
    dob: new Date("2004-08-12"),
    parentage: "Sarah Smith",
    contact: 9967707765,
    address: "789 Elm Street, Village, Country",
  },
  {
    rollno: "A009",
    name: "Michael Davis",
    standard: "3",
    teacher: "Mrs. Johnson",
    subject: "English",
    marks: "74",
    dob: new Date("2004-08-12"),
    parentage: "David Davis",
    contact: 1853692461,
    address: "321 Cedar Road, County, Country",
  },
  {
    rollno: "A0010",
    name: "Sophia Wilson",
    standard: "12",
    teacher: "Mr. Anderson",
    subject: "Physics",
    marks: "99",
    dob: new Date("2004-08-12"),
    parentage: "Olivia Wilson",
    contact: 8591024661,
    address: "567 Pine Lane, City, Country",
  },
];

module.exports = studentsData;
